- name: Installing multiple packages using loops
  hosts: mongodb
  become: yes
  tasks:
  - name: Installing git and postfix
    ansible.builtin.yum:
      msg: "Now Installing is ready"
      name: "{{item}}"
      state: installed
    loop:
    - git
    - postfix